version: '3.7'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - path: .env
        required: true
    environment:
      REDIS_URL: redis://redis:6379
