name: CI

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    environment:
      name: Test
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Run tests
      run: pnpm test

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload Artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./packages/core/coverage/lcov-report

    - name: Deploy Pages
      uses: actions/deploy-pages@v4
      id: deployment
